### ISSUE TITLE
Slow performance on API timeouts?

### ISSUE THREAD

**Issue by mrisher** [HubitatCommunity/DarkSky.net-Weather-Driver#5]
Hi:
I installed the DarkSky driver a week ago and since then, have been experiencing occasional severe performance degradation. I checked the logs and see a lot of `DarkSky.net Weather Driver WARNING: DarkSky weather api did not return data` errors every five minutes for the past several hours. In the Preferences, I have the refresh time set to 3h for both day and night.

I tested my API key with a REST call and by manually refreshing the driver and all seems okay; any other debugging suggestions?

Thank you.

**Comment by Scottma61** [comment]
All support is provided through the Hubitat Community here:  https://community.hubitat.com/t/release-darksky-net-weather-driver-no-pws-required/22699
